
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: aggregate_yo_development

  host: localhost

test:
  <<: *default
  database: aggregate_yo_test

production:
  <<: *default
  database: aggregate_yo_production
  username: aggregate_yo
  password: <%= ENV['AGGREGATE_YO_DATABASE_PASSWORD'] %>
