locations =
Location.create(name: 'Oahu', slug: 'Oahu')
Location.create(name: 'Big Island', slug: 'Big-Island')
Location.create(name: 'Austin', slug: 'Austin')
Location.create(name: 'San Antonio', slug: "San-Antonio")
Location.create(name: 'New York City')
Location.create(name: 'Boston')
Location.create(name: 'Chicago')
Location.create(name: 'Denver')
Location.create(name: 'Miami, FL', slug: "Miami")
Location.create(name: 'Charleston')
Location.create(name: 'Hawaii')
Location.create(name: 'New Orleans')
