locations =
Location.create(name: 'New York City')
Location.create(name: 'Chicago')
Location.create(name: 'Denver')
Location.create(name: 'Ft. Lauderdale')
Location.create(name: 'Miami, FL')
Location.create(name: 'Hawaii')
Location.create(name: 'New Orleans')
Location.create(name: 'Philadelphia')
Location.create(name: 'Seattle')
Location.create(name: 'Washington, D.C.')
